# SPDX-License-Identifier: Apache-2.0
# # Copyright (c) 2020 Intel Corporation
#
# ---
#
- debug:
    msg: "Copying Dynamic Controller IP change feature files"

- name: Remove controller_ip directory, if exists
  command: rm -rf /opt/controller_ip/

- name: Copy inventory to /opt/controller_ip directory
  copy:
    src: ../../../inventory.ini 
    dest: /opt/controller_ip/
    mode: '666'

- name: Copy ip_change.yml to /opt/controller_ip directory
  copy:
    src: ../../../ip_change.yml
    dest: /opt/controller_ip/
    mode: '666'

- name: Copy IPchange.sh to /opt/controller_ip directory
  copy:
    src: ../../../IPchange.sh
    dest: /opt/controller_ip/
    mode: '1777'

- name: Copy cron_task.sh to /opt/controller_ip directory
  copy:
    src: ../../../cron_task.sh
    dest: /opt/controller_ip/
    mode: '1777'


- name: Run the cron_task script
  shell: /opt/controller_ip/cron_task.sh 

